### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by liach**
Updates to modern gradle 7.1.1. The `build` task runs fine on java 8 (but not on 16, see #7 and #12 as the old api is removed).

Needs more check on the publishing parts.

### CODE REVIEW

**Comment by liach** [comment]
Probabaly unneeded now

**Comment by Marcono1234** [comment]
Some of these changes would probably still be useful:
- Replacing usage of `compile` and `testCompile`
- Using Shadow
That would probably also easily allow publishing both the regular artifacts (e.g. for projects using Procyon as library) and the fat jar
- Updating Gradle wrapper scripts and jar (it looks like this is missing from e97d220e99192c267bc7bbbf488546254822a9d1)

**Comment by liach** [comment]
Yeah, I plan on working on the current develop later. A potential problem with this is that since maven plugin is getting deprecated, I am not sure if the replacements from maven-publish is totally right and need to find a repo to test the feature a bit.

**Comment by mstrobel** [comment]
Yeah, Gradle 7 didn't like the maven deployment stuff, so I upgraded to the latest wrapper in the 6.x line.  It's not as if I'm using a whole lot of functionality anyway--it's a pretty simple gradle project.

**Pull request closed without merging**
